### ISSUE TITLE
Is there a way to mark a pet as collected and hide it?

### ISSUE THREAD

**Issue by fraerie** [GurliGebis/WoWAddon-BattlePetCompletionist#4]
I can't leave comments on the Curse page - is there a way to hide pets you've already collected?

As it stands the addon shows TOO MUCH information to be useful, as you can't sperate out the pets you have collected from the ones your missing.

**Comment by GurliGebis** [comment]
If you open the options dialog, you can select to only show missing pets 🙂

**Comment by GurliGebis** [comment]
The "Map pins to include" option in here: https://raw.githubusercontent.com/GurliGebis/WoWAddon-BattlePetCompletionist/main/images/options.webp

**Comment by Rezy942** [comment]
Was going to open a separate issue but perhaps this is related in a way - its correct you can filter to show only uncollected. Thats fantastic! 

My minor gripe is difficulty of adjusting these settings on the fly.
Example: In DF i collected 99% of the pets, i want to have this setting enabled to track down those last few over time as I do WQ etc.
But when I go to old content, my map is basically full of these icons, and therefore unusable.

Solution: A way to quickly toggle the map icons feature without having to go via addon options.
Preferably as a checkbox in the map drop down, or another separate icon that is anchored to the rest icons:
![image](https://github.com/GurliGebis/WoWAddon-BattlePetCompletionist/assets/122007087/999fed20-f870-471f-a741-b4f205492616)

This toggle would be saved across logins and all characters (i'd prefer it to be global toggle, instead of having to log each one of my alts and have to check it constantly)

I believe PetTracker did something like this, although the worst possible way.
Thank you :)

**Comment by GurliGebis** [comment]
I know about it being like that in PetTracker, but looking at how the author of PetTracker feels about open source (up until recently he pretended his addons was open source, but with all permissions removed from the user), I don't want to do that, since he would just claim I copied the code from him (the way I would do it is close to how he did that).
Instead, I have moved all the settings into the options dialog, so it is in one place, instead of spread all over, like it is in his addon.

A shortcut is the minimap button, which opens the options dialog, allowing for easily changing the filtering.

**Comment by Rezy942** [comment]
> I know about it being like that in PetTracker, but looking at how the author of PetTracker feels about open source (up until recently he pretended his addons was open source, but with all permissions removed from the user), I don't want to do that, since he would just claim I copied the code from him (the way I would do it is close to how he did that). Instead, I have moved all the settings into the options dialog, so it is in one place, instead of spread all over, like it is in his addon.
> 
> A shortcut is the minimap button, which opens the options dialog, allowing for easily changing the filtering.

Understandable! Unfortunately users of many different addon that use minimap "button bag" have to go through multiple clicks including finding the actual addon icon, then selecting the drop down menu, and applying. This takes way too long (personally) to do on the fly - in which case I will just not use the feature until I absolutely have to.
Not a huge issue, just extremely anti-QoL. You could technically add a modifier key on minimap button press which would toggle icon view, and not have the issue of "copying" another addon.

**Comment by GurliGebis** [comment]
I will see what I can do, I hope to find a good way to do it, without running into issues.

**Comment by GurliGebis** [comment]
@Rezy942 I have implemented a checkbox for disabling/enabling (remember last selection when re-enabling) - next version will have it: 
![billede](https://github.com/GurliGebis/WoWAddon-BattlePetCompletionist/assets/13592619/4a33c2f6-8aa6-428b-ab0d-5193945a35d0)

**Comment by Rezy942** [comment]
> 

Thank you SO much!!

**Comment by GurliGebis** [comment]
@Rezy942 you're welcome 🙂
