### ISSUE TITLE
Another complete hotbar taint

### ISSUE THREAD

**Issue by CrusaderEsper** [GurliGebis/WoWAddon-BattlePetCompletionist#52]
1x [ADDON_ACTION_BLOCKED] AddOn 'BattlePetCompletionist' tried to call the protected function 'PetActionBar:SetShownBase()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetShownBase'
[string "@Blizzard_ActionBar/Mainline/ActionBar.lua"]:330: in function `UpdateVisibility'
[string "@Blizzard_ActionBar/Mainline/ActionBar.lua"]:324: in function `originalHide'
[string "@Blizzard_FrameXMLBase/Mainline/FrameLocks.lua"]:137: in function <Blizzard_FrameXMLBase/Mainline/FrameLocks.lua:113>
[string "@Blizzard_FrameXMLBase/Mainline/FrameLocks.lua"]:148: in function <Blizzard_FrameXMLBase/Mainline/FrameLocks.lua:141>
[string "@Blizzard_FrameXMLBase/Mainline/FrameLocks.lua"]:166: in function `Hide'
[string "@Blizzard_ActionBar/Mainline/PetActionBar.lua"]:172: in function <Blizzard_ActionBar/Mainline/PetActionBar.lua:119>
[string "=[C]"]: in function `Update'
[string "@Blizzard_ActionBar/Mainline/PetActionBar.lua"]:83: in function <Blizzard_ActionBar/Mainline/PetActionBar.lua:70>
[string "=[C]"]: ?

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}

Playing a druid, got into combat in aquatic form after having done a pet battle earlier in my play session.

**Comment by GurliGebis** [comment]
It's a false positive - this addon doesn't call the mentioned function.
What is happening is that some addon calls a protected function, causing a taint.
Then later on, some other addon does something else, trips over it, and the error is shown.

It's pretty difficult to debug, since there can be quiet a while between the taint and the trip.

If you can replicate the issue reliably, please try and disable all other addons than this one, and see if it happens then.
If it does with this one as the only one loaded, please reopen with a link to a short video showing how to reproduce the issue 🙂

Sorry for not being able to help resolve it better.
