### ISSUE TITLE
Add Compatibility for Titan Panel pls

### ISSUE THREAD

**Issue by tatatada** [GurliGebis/WoWAddon-BattlePetCompletionist#8]
see Topic, thx

**Comment by GurliGebis** [comment]
It looks like Titan Panel already supports taking minimap buttons and presenting them.

![billede](https://github.com/GurliGebis/WoWAddon-BattlePetCompletionist/assets/13592619/d6654bed-c030-44e5-99c4-dd6dfae5b4cc)

So since it would be doing the same thing, I don't see a reason to implement it separately, since it would just be duplicating what the built-in functionality already does.
